### ISSUE TITLE
test error 

### ISSUE THREAD

**Issue by erhuodaosi** [SeitaroShinagawa/chainer-partial_convolution_image_inpainting#24]
I had trained my model  successfully,and as a result,it eventually generated model500000.npz.
When I print "python generate_result.py -g 0 --load_model result/model500000.npz" on my terminal,an error happened.I had tried many ways to solve this problem but in vain.

The question is listed as below:

python generate_result.py -g 0 --load_model result/model500000.npz

Namespace(batch_size=4, crop_to=256, eval_folder='generated_results', gpu=0, load_dataset='place2_test', load_model='result/model500000.npz', resize_to=256)
loading vgg16 ...
ok
Completion model loaded
use gpu 0

Traceback (most recent call last):
File "generate_result.py", line 114, in
main()
File "generate_result.py", line 73, in main
batch = val_iter.next()
File "/home/fl/.local/lib/python3.6/site-packages/chainer/iterators/serial_iterator.py", line 48, in next
self._previous_epoch_detail = self.epoch_detail
File "/home/fl/.local/lib/python3.6/site-packages/chainer/iterators/serial_iterator.py", line 86, in epoch_detail
return self.epoch + self.current_position / len(self.dataset)
ZeroDivisionError: division by zero

What can I do to solve this problem?I will very appreciate if you could help me,thank you!

**Comment by erhuodaosi** [comment]
Traceback (most recent call last):
  File "generate_result.py", line 114, in <module>
    main()
  File "generate_result.py", line 73, in main
    batch = val_iter.next()
  File "/home/fl/.local/lib/python3.6/site-packages/chainer/iterators/serial_iterator.py", line 48, in __next__
    self._previous_epoch_detail = self.epoch_detail
  File "/home/fl/.local/lib/python3.6/site-packages/chainer/iterators/serial_iterator.py", line 86, in epoch_detail
    return self.epoch + self.current_position / len(self.dataset)
ZeroDivisionError: division by zero

**Comment by xiejiamingly** [comment]
I have the same prblem，how did you solve it?

**Comment by Prudvi01** [comment]
Have you figured it out? I seem to have a similar problem.

**Comment by erhuodaosi** [comment]
@Prudvi01 Please check your dataset load
